source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.2'
use_frameworks!

# Replace `<Your Target Name>` with your app's target name.
target 'RateMyCourseWashU' do
  pod 'PusherChatkit'
end